version: '3.1'

services:

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accounts
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/registration-login-spring-xml-maven-jsp-mysql/src/main/resources/db.sql:/docker-entrypoint-initdb.d/db.sql
  web:
    build: ./
    ports:
      - "443:8080"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accounts
      MYSQL_USER: root
      JDBCURL: db
    depends_on:
      - db

