apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: registration-form-deploy-app-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: registration-form-deploy-app
  minReplicas: 4
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
