apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registration-form-pv-claim
  labels:
    app: registration-form-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
